### ISSUE TITLE
canバスのコネクタの位置

### ISSUE THREAD

**Issue by hayate2718** [mukuchin/SympleSensorBoard#1]
canバスのコネクタをx=25.4になるように設計して。あと、現状の基板図では問題ないけど、書き込み用コネクタの両端の周辺は背の高い部品は置かないで。フラットケーブルについてるコネクタの大きさ見ればわかると思うけど両端がはみでるんだよね。

**Comment by mukuchin** [comment]
了解です。直しておきます。
